sudo: false
language: python
python: 3.6
env:
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=lint
install: pip install tox
script: tox -e $TOXENV
notifications:
  email: false
  irc: "irc.freenode.org#XelNext"
